### ISSUE TITLE
Add AWS Cognito as Authentication Service for LLM Application

### ISSUE THREAD

**Issue by kkiani** [DataChefHQ/damavand#26]
# Description
Integrate AWS Cognito as the authentication service for LLM applications built using Damavand. This will provide secure user authentication and authorization for applications deploying Large Language Models (LLMs) on AWS.

# Key Tasks:

- [ ] Integrate AWS Cognito to manage user authentication for the LLM application.
- [ ] Integrates with the AwsLlmComponent.
- [ ] Ability to disable it.

# Acceptance Criteria:

- AWS Cognito is integrated into the LLM component.
- Documentation and examples are available to guide developers on implementing user authentication with Cognito.

**Comment by bramelfrink** [comment]
Just had a call with @kkiani , it seems that this issue needs to be rephrased. 

The goal is to introduce a mechanism to authenticate users / applications that is in line with the OpenAI specification, which uses an API key. This way, it can be cloud agnostic and not depend on e.g. Cognito user pools.

**Comment by kkiani** [comment]
Closing this as this is implemented and integrated.
